version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: campusfind-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - campusfind-network

  backend:
    image: taskflowregistry.azurecr.io/campusfind-backend:latest
    container_name: campusfind-backend
    restart: always
    command: sh -c "node setup.js && node server.js"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - uploads-data:/usr/src/app/uploads
    depends_on:
      - mongodb
    networks:
      - campusfind-network

  frontend:
    image: taskflowregistry.azurecr.io/campusfind-frontend:latest
    container_name: campusfind-frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - campusfind-network

volumes:
  mongo-data:
  uploads-data:

networks:
  campusfind-network:
    driver: bridge
